In [59]:
import numpy as np
a = np.arange(10, 30).reshape(4, 5)
print(a)

red = a[0, 1:4]
blue = a[::2, 4]
lightblue = a[:, 1::2]
print(lightblue)
yellow = a[0, 0]
green = a[0:3, 2]
print(green)
print(blue)




[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[11 13]
 [16 18]
 [21 23]
 [26 28]]
[12 17 22]
[14 24]
